### ISSUE TITLE
"Packet" and "datagram"

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#106]
I think that the older versions of the spec were good at using the term "datagram" to refer to the thing that holds DTLS records.  This version now uses "packet" in a good number of places.  Sometimes I think that it means "record", other times "datagram".

I'm sure that this is just the influence of QUIC and it can be fixed easily.

**Comment by ekr** [comment]
Actually 6357 uses "packet" all over the place. I'll do an audit, but I'm not going to ones that mean IP packet.
