### ISSUE TITLE
Improve ACK advice

### ISSUE THREAD

**Issue by ekr** [tlswg/dtls13-spec#128]
Hanno Becker writes:

I have a minor comment on DTLS 1.3 draft 37.

On the topic of sending ACKs, the draft recommends:

```
ACKs SHOULD NOT be sent for other complete
flights because they are implicitly acknowledged by the receipt of
the next flight, which generally immediately follows the flight.
```

I wonder if the case of post-handshake authentication should be
explicitly mentioned as a potential exception to this rule, since
the TLS 1.3 RFC explicitly mentions that responses to
`CertificateRequest` may be delayed in some contexts:

```
Note: Because client authentication could involve prompting the user,
servers MUST be prepared for some delay, including receiving an
arbitrary number of other messages between sending the
CertificateRequest and receiving a response.
```

In this case, it would be beneficial to immediately explicitly ACK
the `CertificateRequest` message even though it is also implicitly
acked through the eventual response via the `Certificate` message.

**Comment by rtatnet** [comment]
roufique.yml

**Comment by rtatnet** [comment]
> Hanno Becker writes:
> 
> I have a minor comment on DTLS 1.3 draft 37.
> 
> On the topic of sending ACKs, the draft recommends:
> 
> ```
> ACKs SHOULD NOT be sent for other complete
> flights because they are implicitly acknowledged by the receipt of
> the next flight, which generally immediately follows the flight.
> ```
> 
> I wonder if the case of post-handshake authentication should be
> explicitly mentioned as a potential exception to this rule, since
> the TLS 1.3 RFC explicitly mentions that responses to
> `CertificateRequest` may be delayed in some contexts:
> 
> ```
> Note: Because client authentication could involve prompting the user,
> servers MUST be prepared for some delay, including receiving an
> arbitrary number of other messages between sending the
> CertificateRequest and receiving a response.
> ```
> 
> In this case, it would be beneficial to immediately explicitly ACK
> the `CertificateRequest` message even though it is also implicitly
> acked through the eventual response via the `Certificate` message.

roufique.yml

**Comment by Kxuan** [comment]
Hi Ekr,

Regarding the ACK of the CertificateRequest, I think we have one more place to modify.

TLS 1.3 RFC saids the server may send multiple CertificateRequests to the client in "close succession", and the Client can respond to them in a different order: 
```
   In addition, clients
   which receive multiple CertificateRequests in close succession MAY
   respond to them in a different order than they were received (the
   certificate_request_context value allows the server to disambiguate
   the responses).
```

We should treat each of CertificateRequests as `individual flight`. A `Certificate` response from client does not implicitly acknowledge to all CertificateRequests. The server should continue to retransmit other CertificateRequests which is not responded by the `Certificate`.

So the text should be changed from :
```
Each NewSessionTicket or KeyUpdate is an individual flight; in particular, a KeyUpdate sent in response to a KeyUpdate with update_requested does not implicitly acknowledge that message.
```
To
```
Each NewSessionTicket, KeyUpdate or post-handshake CertificateRequest is an individual flight;
in particular, a KeyUpdate sent in response to a KeyUpdate with update_requested
does not implicitly acknowledge that message.
```

Thanks,

Zhai Zhaoxuan
