### ISSUE TITLE
Should we require CIDs on all packets

### ISSUE THREAD

**Issue by ekr** [tlswg/dtls13-spec#144]
Hanno Becker points out that the current text does not cryptographically protect the CID when we have coalesced packets. I created PR #143 to add this feature, but I think instead we should simply require that all packets have CIDs once the CID is established. This seems like a net reduction in complexity. There would be two changes here:

1. Re-emphasize the point already in the DTLS CID spec that you abort if a CID is expected and none is found.
2. Remove the text about allowing implicit CIDs.

**Comment by chris-wood** [comment]
This was resolved by #148. Please re-open if that's not the case!
