### ISSUE TITLE
DTLS 1.3 header format

### ISSUE THREAD

**Issue by awcunning** [tlswg/dtls13-spec#153]
In the current DTLS 1.3 spec (version 38 - https://www.ietf.org/id/draft-ietf-tls-dtls13-38.txt) there are conflicting DTLS header formats structures defined.

Figure 3 defines the DTLSCiphertext header as comprising of Connection ID (if any, length as negotiated), Sequence Number and then Length field (if present)

Where as Figure 4 defines the dtls header with the Sequence number coming before the connection ID.

Which figure is correct?

**Comment by hannestschofenig** [comment]
Good catch. Fixed in PR#154 - https://github.com/tlswg/dtls13-spec/pull/154

**Comment by hannestschofenig** [comment]
Good

**Comment by awcunning** [comment]
Great. Just one more clarification. From the DTLS 1.2 Connection ID draft we have the following DTLS header format:
        struct {
            ContentType special_type = tls12_cid;
            ProtocolVersion version;
            uint16 epoch;
            uint48 sequence_number;
            opaque cid[cid_length];               // New field
            uint16 length;
            opaque enc_content[DTLSCiphertext.length];
        } DTLSCiphertext;

            Figure 3: DTLS 1.2 CID-enhanced Ciphertext Record.

So the packet formatting is epoch/seqnum/CID/length.
In the DTLS 1.3 Figure 4 we have the following unified header format: CID/ compressed seqnum/length.

Do we have an interoperability issue here for Connection ID between DTLS 1.2 and 1.3 header formats?

Regards
Andy

**Comment by bogroza** [comment]
DTLS 1.2 and DTLS 1.3 do not share the same header format.
