### ISSUE TITLE
Explain differences between DTLS 1.2 CID and DTLS 1.3 in the appendix

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/dtls13-spec#158]
In both versions of DTLS we have to do the extension negotiation because you have to agree on the CID values. 

In both versions we have to carry the CID in the record layer (if the CID is used). The way we incorporated the CID into the headers is different between the different versions. In DTLS 1.3 we have this variable length header and in DTLS 1.2 we don't. 

There are also privacy differences.

**Comment by ekr** [comment]
I'm inclined not to add anything here. If you feel strongly maybe you could provide a PR?

**Comment by kaduk** [comment]
I think the privacy differences (and ability to change values over the lifetime of an association, e.g., when roaming) are probably worth mentioning.  @hannestschofenig do you plan to write some text?  If not I can try to squeeze it in.

**Comment by hannestschofenig** [comment]
PR is available at #198

**Comment by chris-wood** [comment]
Fixed in #198. Closing.
