### ISSUE TITLE
Say something about how large cert messages may cause congestion

### ISSUE THREAD

**Issue by ekr** [tlswg/dtls13-spec#174]

**Comment by hannestschofenig** [comment]
DTLS 1.3 does not really change this aspect compared to earlier DTLS versions. 

We could reference a number of the other TLS WG documents that attempt to reduce the size of the certificate message, such as 
* Client Certificate URL
* Cached Info
* Certificate Compression
* Following the guidelines in RFC 7925
* Other certificate types

It may be possible to use the fragmentation mechanism to send one certificate after the other in the certificate chain. 

Is this what you had in mind?
