### ISSUE TITLE
Feedback by Éric Vyncke 

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/dtls13-spec#225]
== COMMENTS ==

-- Section 3 --
s/TLS cannot be used directly in datagram environments/TLS cannot be used directly over a datagram transport/ ?

[Hannes] DTLS is also used over non-IP-based networks (e.g. LoRaWAN, NB IoT, Bluetooth Smart) and "datagram transport". What would be the right term to describe "environments" that include transport layer protocols like UDP as well as those non-IP-based networks?

Bullet 2) s/to enable reassembly in the correct order/to enable reordering/ ?

[Hannes] The complete sentence is:

"
       The DTLS handshake includes message
       sequence numbers to enable reassembly in the correct order in
       case datagrams are lost or reordered.
"

I believe that saying sequence numbers enable reassembly in the correct order is correct. 

-- Section 3.1 --
Should there be a hint to a maximum retry count ?

[Hannes] There will be a retry count in an implementation. Do we need to say that if we don't have a number to suggest? Not sure. 

-- Section 3.3 --
I understand the motivation (and no need to reply), but, sigh... implementing frag/reassembly above the transport layer...

[Hannes] Seems to be common these days. Examples: CoAP, and QUIC

**Comment by kaduk** [comment]
I don't think I found the PR to match up with the "pr-exists" label; could I get a pointer?

**Comment by ekr** [comment]
My bad. https://github.com/tlswg/dtls13-spec/pull/240
