### ISSUE TITLE
AEAD Limits

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/dtls13-spec#235]
Francesca says

>    Any TLS cipher suite that is specified for use with DTLS MUST define
>    limits on the use of the associated AEAD function that preserves
>    margins for both confidentiality and integrity.  That is, limits MUST
>    be specified for the number of packets that can be authenticated and
>    for the number of packets that can fail authentication before a key
>    update is required.  Providing a reference to any analysis upon which
>    values are based - and any assumptions used in that analysis - allows
>    limits to be adapted to varying usage conditions.
> 
> FP: This seems important enough that it should be highlighted for the experts reviewing the registration. I see that https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4 has a number of notes, maybe that would be enough, or maybe add it (as an update?) to RFC 8447?

I am uncertain whether this document is the right place to place restrictions on IANA for this purpose beyond what has already been done elsewhere. Maybe there is a chance to do something in the TLS 1.3 update.

**Comment by ekr** [comment]
I added some text to the PR.

**Comment by kaduk** [comment]
Since #234 got merged, should this issue be closed now?
