### ISSUE TITLE
Retransmissions

### ISSUE THREAD

**Issue by hannestschofenig** [tlswg/dtls13-spec#236]
Bernard writes: 

> [BA] Is it always possible to distinguish a retransmission from a late
> arrival of an original packet? This seems like it could result in
> wrongly resetting the timer in some situations.
> 
> [BA] How does the implementation know how much of the flight to send?
> 
> [BA] For the fatal alert case, it does seem like retransmission would
> be a good idea; otherwise the peer can be left hanging.
> 
> 
> Section 7.1 "Disruptions" such as reordering do not affect timers, correct?
> ACKs SHOULD NOT be sent for these flights unless generating the responding flight takes significant time.
> What is "significant time"?

**Comment by ekr** [comment]
>  [BA] Is it always possible to distinguish a retransmission from a late
    arrival of an original packet? This seems like it could result in
    wrongly resetting the timer in some situations.

No, because if there are any retransmissions you shouldn't reset.


>     [BA] How does the implementation know how much of the flight to send?

We just give some guidance and let them sort it out. There's no really good answer.


>     [BA] For the fatal alert case, it does seem like retransmission would
    be a good idea; otherwise the peer can be left hanging.

DTLS has been this way for some time, and there's no really obvious way to deal with it, so i think we leave as-is.

>    Section 7.1 "Disruptions" such as reordering do not affect timers, correct?

Yes. How could they.


>    ACKs SHOULD NOT be sent for these flights unless generating the responding flight takes significant time.
>    What is "significant time"?

Changed this to "immediate"

**Comment by hannestschofenig** [comment]
Regarding: 

> [BA] How does the implementation know how much of the flight to send?

I guess the question is about whether one or multiple handshake messages are packed in single underlying datagram. 

I would say it depends a bit on the use case and the PMTU size.  If there is enough space (PMTU-wise) then it may be good in some cases to wait until a number of messages are ready for transmission. In other cases, it may be better to transmit the messages right away individually without packing.

**Comment by ekr** [comment]
@chris-wood I propose we just close this.

**Comment by chris-wood** [comment]
That seems reasonable. @ekr, please feel free to close with no action.
