### ISSUE TITLE
Should the protocol specify a mechanism to ensure that the link is disconnected if the peer is restarted or some reason?

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [tlswg/dtls13-spec#248]
Since there are various versions of dtls implementations, should the protocol specify a common mechanism for disconnects? When the status of the peer end is unknown.

**Comment by ekr** [comment]
Generally, I think that's out of scope at this time. We could graft
something like QUIC's stateless reset on later if needed, but DTLS has
gotten along pretty well without it so far

**Comment by yangyangtiantianlonglong** [comment]
```DTLS has gotten along pretty well without it so far```
When disconnecting a dtls link with a third-party device, there is no common disconnection mechanism and we are always speculating on the behavior of the third-party device. Most dtls users disconnect the link by timeout, and setting different times will cause confusion. And timeout disconnection makes app user experience poor. It would make things easier to suggest a common mechanism to solve the problem.

**Comment by ekr** [comment]
I'm not saying this wouldn't be helpful. I'm saying that at this point in
the process it would be disruptive to hold the document to add it.
Moreover, we would probably add something like QUIC's stateless reset,
which would end up being an extension anyway. So I think the right thing to
do is to write an extension document.

**Comment by yangyangtiantianlonglong** [comment]
I see. Thank you for your reply.

**Comment by seanturner** [comment]
@ekr should this be closed?

**Comment by ekr** [comment]
yes imo
