### ISSUE TITLE
DTLS 1.3 limits the number of packets that can be encrypted with AES-GCM to 2^40.5

### ISSUE THREAD

**Issue by emanjon** [tlswg/dtls13-spec#249]
If I have understood and calculated correctly DTLS 1.3 limits the number of
packets in a AES-GCM connection to 2^40.5 compared to 2^64 in DTLS 1.2. This
is quite a severe limitation that is not mentioned explicitly. The AEAD limits
in themselves are not a problem, but the combination of AEAD limits (2^24.5)
and a small epoch (2^16) is a problem.

I think this is major problem in some use cases of DTLS. E.g. most 3GPP 5G use
cases where DTLS or DTLS/SCTP is used for semi-permanent connections (lasting years)
and where the terminating the connection cause severe disturbances.

I did not find any discussion about this problem (but I could easily have missed it)

It is known that the limit of 2^48 packets in SRTP can be reached and 2^40.5 is
significantly smaller than this...

If the document was not in such a late stage, I would have suggested to increase the size
of the epoch to 32 bits.....

I think this and the other problems DTLS 1.3 has with semi-permanent connections has to be
solved sooner than later.

**Comment by ekr** [comment]
@emanjon thanks for filing this. I hear you about the late stage, but IIRC we never represent the entire epoch on the wire in any case, so it seems like just changing it to 32 bits would be pretty easy, so why not do it now?

**Comment by kaduk** [comment]
How do the chacha20 numbers compare to the AES-GCM ones?

**Comment by emanjon** [comment]
@kaduk I don't think (D)TLS 1.3 puts any limits on ChaCha20 so my understanding
is understanding is that the total number of packets can be protected in the current drafts is

ChaCha20 2^64 (2^48 * 2^16)
AES-GCM 2^40.5 (2^24.5 * 2^16)
AES-GCM 2^39 (2^23 * 2^16)

**Comment by emanjon** [comment]
@ekr I am all for changing this now. I made a PR #250 that change epoch from uint16 to uint32. As you say, it seems like a pretty easy change to do.

Is uint32 the right size?

**Comment by ekr** [comment]
Unless you think we should do uint64.

@kaduk @chris-wood what would we have to do to make this change?

**Comment by emanjon** [comment]
https://github.com/gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis/issues/63

- Magnus Westerlund thinks uint64 would be a safer bet.

- Michael Tüxen suggest to wrap the uint16 epoch instead. That might be an easier solution. I don't see a direct problem in DTLSPlaintext, ACK message, or record_sequence_number with a uint16 epoch that is allowed to wrap like:

4, 5, ... 2^16-1, 4, 5, ... 2^16-1, 4, 5, ...

**Comment by seanturner** [comment]
@ekr @kaduk @chris-wood since it's through the IESG we would need to at least raise that this change was made after they had approved it.  I suspect that doing some kind of 2-week heads up to the WG/IESG that we want to make the change before landing it. But, if we do that or something more drastic that's really up to @kaduk.

**Comment by gloinul** [comment]
I want to point out that allowing wrapping per #252 may not be the best solution if one considers to use the DTLS epoch as part of the input to the TLS exporter as suggested in #253. Then one want an input that doesn't wrap, and then to ensure that one doesn't practically run into any limits, then an uint64 would be better. 

An unit32 appears to be sufficient for a quite extreme use case with minimal messages size (which is one DTLS record with 4 byte user message) and high bandwidth (10 Gbps) sustained over a period of more than 5 years before the epoch would wrap. However, to my understanding the full epoch value are so rarely included in transmitted DTLS messages that its size have minimal implication on the overhead that it is not worth saving 4-bytes to be certain to have eliminated any practical limitation.

**Comment by kaduk** [comment]
> @ekr @kaduk @chris-wood since it's through the IESG we would need to at least raise that this change was made after they had approved it. I suspect that doing some kind of 2-week heads up to the WG/IESG that we want to make the change before landing it. But, if we do that or something more drastic that's really up to @kaduk.

I think a 2-week WGLC and notifying the IESG will suffice.

**Comment by emanjon** [comment]
FYI. We have now run into quite many problems with the interworking of semi-permanent DTLS/SCTP connections (lasting years) and DTLS 1.3:

- No Diffie-Hellman rekeying
- No post-handshake server authentication
- No rekeying of the exporter_secret
- 2^40.5 packets limit
- 2 minute MSL requirement
- 2^38.5 byte SCTP user message size limit

Our initial plan was to just replace DTLS 1.2 with DTLS 1.3, leave DTLS/SCTP as is, but as the problems keep adding up we are now startnig to consider quite big changes to DTLS/SCTP 1.3 to make this work:
https://github.com/gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis/issues/52

Using new DTLS connections instead of KeyUpdate could potentially address the first five, but is a significant change.
