### ISSUE TITLE
Mention RFC 7457 in Security section

### ISSUE THREAD

**Issue by elvey** [tlswg/dtls13-spec#254]
I think it makes sense to refer to [RFC 7457](https://datatracker.ietf.org/doc/rfc7457/), "Summarizing Known Attacks on Transport Layer Security (TLS) and Datagram TLS (DTLS)" from the Security Considerations section.
I think this would just be an informative reference.  Would improve the draft, IMVHO. 

<sup>(Hopefully I'm following [CONTRIBUTING.md](https://github.com/tlswg/dtls13-spec/blob/master/CONTRIBUTING.md) by opening this issue.  If such a Security Considerations section change is considered to change the spec, and 1+ editors support a change like this then I should post to the list? [8/15 edit: It's in today's GitHub digest; hope it garners a response.])</sup>

**Comment by elvey** [comment]
@ekr ?

**Comment by martinthomson** [comment]
Weird.  That comment is 7 days old, but I only saw it today.  I think that this might be fine/harmless, but the draft is pretty far through the process.  I would leave this to the editor, but note that proposing a change (with a pull request) would give you the best odds of any citation happening.

**Comment by elvey** [comment]
Thanks, @martinthomson.  OK, I made a pull request; perhaps I did it right and it's helpful. 
@ekr @hannestschofenig?  I guess this is just an easy editorial change.  Is discussion needed on the mailing list?

(Off/separate topic: I don't understand why https://www.ietf.org/archive/id/draft-ietf-tls-dtls13-43.html#name-informative-references has so many more references than the version here.)

**Comment by seanturner** [comment]
While it might be harmless to add this reference, I am not really sure it is needed. Do all of the attack apply to DTLS 1.3?

RFC 7457 motivated RFC 7525 (aka BCP 195). There is currently a 7525bis (an update) that will address (D)TLS1.3. I would argue that the 7525bis is what we care about but DTLS1.3 won't point to it, 7525bis will point to the DTLS 1.3 RFC.

spt

**Comment by ekr** [comment]
I think we shouldn't add this for hte reason Sean mentions.
