### ISSUE TITLE
Prohibit concurrent NST and KeyUpdate

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#26]
The logical way to implement these is to reuse the same retransmission and ACK logic and timers as you use during the handshake.  Having multiple concurrent exchanges in progress is possible in theory, and it might even be possible to retain the same timers by delaying responses to a transaction, but it would be easier to implement if you only had to worry about one at a time.

**Comment by ekr** [comment]
I don't think that this is going to work:

1. If the KeyUpdate and NST come from the same person, then they get to choose what to do and the other party ACKs the same way no matter what.

2. If the client sends KeyUpdate.update_requested and the server sends NST, then there's now way to prohibit these, so you're kinda back in the soup, though we could make an exception that says you don't *have* to send KeyUpdate immediately if you have another transaction in process.

**Comment by ekr** [comment]
Closing. Feel free to re-open
