### ISSUE TITLE
Peer Address Update

### ISSUE THREAD

**Issue by emanjon** [tlswg/dtls13-spec#267]
The DTLS 1.2 Connection ID draft (soon-to-be-RFC9146) section on "peer address update" and the text in DTLS 1.3 seems quite different.

https://www.rfc-editor.org/rfc/authors/rfc9146.html#name-peer-address-update

The "unless they first perform some reachability test" seems preferable to the soft text in soon-to-be-RFC9146, but DTLS 1.3 seems to be missing the DTLS 1.2 requirement on "The received datagram is "newer"". Feels spontanously like DTLS 1.2 and 1.3 should have similar requirements/guidance on "peer address update".

FYI, I started writing some analysis of Peer Address Update in a draft that I intend to submit to T2TRG
https://github.com/EricssonResearch/coap-actuators/blob/master/draft-mattsson-t2trg-amplification-attacks.md

**Comment by emanjon** [comment]
- Would be good to warn implementations that clients must not update the permanent server address based on the “Peer Address Update” mechanism. Using IP addresses instead of DNS names is not uncommon in e.g., IoT, DNS over DTLS (RFC 8094), and 3GPP DTLS interfaces. An client updating the permanent server address based on an MITM attack could be unable to recover.

- Would be good with a sentence or two on the problems changing the IP address of a gateway multiplexing a lot of DTLS connections with Connection ID. All the client and servers would have to send at least one record before the old IP address can be deactivated. Might take some time in a IoT deployment.

**Comment by ekr** [comment]
I tend to think we should at most provide warnings about how it's dangerous. @emanjon would you be willing to provide a quick PR?

**Comment by ekr** [comment]
In the interest of being done I opted for basically punting it to a future spec.

**Comment by ekr** [comment]
https://github.com/tlswg/dtls13-spec/pull/270
