### ISSUE TITLE
Connection ID liveness

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#52]
This mirrors an open topic of discussion in QUIC, and I assume that we'll want to take the lessons learned there and probably copy whatever the conclusion is.

The problem is that the current design has a server remember all connection IDs that it ever minted.  Over time, that might be infeasible for a server.  It might be good to limit the number that are in use.

**Comment by ekr** [comment]
This isn't correct. In DTLS, as opposed to QUIC, new connection IDs may be marked as ```cid_immediate```, in which case the peer is required to stop using any old CIDs immediately. The document could probably use some more text here, but the basic idea is that once a cid_immediate message has been ACKed, you know that any old CIDs are no longer valid.
