### ISSUE TITLE
Connection ID

### ISSUE THREAD

**Issue by ekr** [tlswg/dtls13-spec#6]
https://github.com/ekr/dtls13-spec/issues/6

**Comment by fortuna** [comment]
That link is broken to me: https://github.com/ekr/dtls13-spec/issues/6
@ekr: Your fork seems to have no Issues associated with it. Did you mean a different link?

**Comment by ekr** [comment]
Unfortunately, I messed up my local fork. Bottom line is we should have a connection id to allow bridging over NAT changes, but there are potential privacy issues

**Comment by nmav** [comment]
See our take on that on https://thomas-fossati.github.io/draft-tls-cid/

**Comment by ekr** [comment]
Per WG discussion, this will be done in a separate spec
