### ISSUE TITLE
Shrink the record size

### ISSUE THREAD

**Issue by ekr** [tlswg/dtls13-spec#7]
https://github.com/ekr/dtls13-spec/issues/5

**Comment by martinthomson** [comment]
That link is broken.

The proposal, as I recall, is to reduce the record header to two octets:

The first octet has three bits set to 001 (these allow for DTLS to be distinguished from other protocols that it is [commonly multiplexed with](https://datatracker.ietf.org/doc/html/rfc7983#page-9)).  

The next two bits carry the lowest significant bits of the epoch.  Two bits are necessary to distinguish early data, client handshake, and application data during the handshake.  This might be reduced to a single epoch bit by using a full-sized record header for early data, doubling the sequence number space.

The remaining 11 bits are the lowest significant bits of the record sequence number.  This means that we could be tolerant of [reordering](https://tools.ietf.org/html/rfc6250#section-3.1.8) of 1024 packets.  Assuming 1k packets, this would mean hugely divergent path characteristics, or 1Mb of BDP.  The tweak above for early data would double this, which might be a good idea (it might also be a good idea for other reasons, such as the ability to recognize early data that arrives before a handshake).
