### ISSUE TITLE
Remove prohibition on sending before handshake completion

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#71]
> In particular, it is still impermissible to send data prior to completion of the first handshake.

Aside from the "first" being a vestige of renegotiation, I think that this is wrong.  Clients send 0-RTT before the handshake completes from their perspective; servers send 0.5-RTT data before they believe the handshake is complete.  This needs more nuance.

**Comment by hannestschofenig** [comment]
To me this sentence appears wrong and should be deleted. Here is the PR: 
https://github.com/tlswg/dtls13-spec/pull/94

**Comment by ekr** [comment]
Fixed.
