### ISSUE TITLE
Key separation from TLS

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#72]
Consider whether the key schedule should be separated from TLS.  And, if so, how to do that.

QUIC is debating whether or not to change the label prefix (from "tls13 " to "quic ", for instance), or whether it is better to change only the labels for calculating the key, iv, and sn keys.

**Comment by ekr** [comment]
I don't think this is needed, but I'm happy to bring it up in Prague.

**Comment by martinthomson** [comment]
I agree.  I don't think that it is needed, but we might still discuss it.

**Comment by cjpatton** [comment]
Why wouldn't this be needed? Do you mean it should be valid for a key derived for one protocol to be valid in another? Or do you mean there are other mechanisms that prevent this from happening?

**Comment by ekr** [comment]
Well, the handshake transcript is different because the TLS handshake headers are different from DTLS

**Comment by beurdouche** [comment]
Well, doesn't that happen only after the first message is sent/received. My intuition is that it would be good practice to make sure the labels are different so that you can't use the binder_key across protocols. If I remember correctly, the very first Derive secret is over a PSK and an empty transcript isn't it ?

**Comment by hannestschofenig** [comment]
Was there any conclusion/discussion on this issue?

**Comment by ekr** [comment]
@beurdouche: isn't the binder computation over the prefix of the first handshake message, including the header?

**Comment by beurdouche** [comment]
@ekr Well, I may misunderstand what is happening but when I look at the Key Schedule, I see that the `binder_key` is computed as a `Derive-Secret` over an empty Transcript-Hash, which means that only the PSK contribute to that secret. Am I wrong ?

**Comment by ekr** [comment]
It is, but it's then used to compute the binder over the CH including the handshake header, no?

**Comment by ekr** [comment]
Consensus in Montreal was to be conservative. Probably change "tls13" -> "dtls13", space permititng.

**Comment by martinthomson** [comment]
"dtls3" is an option if we find we're right up against the limit.  But note that QUIC is adding 5 bytes to this string for its use.

**Comment by seanturner** [comment]
@ekr I think this one can safely be closed out.
