### ISSUE TITLE
What about TCP cookies?

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#75]
> DTLS borrows the stateless cookie technique used by Photuris {{RFC2522}} and IKE {{RFC7296}}.

What about TCP?

**Comment by ekr** [comment]
What about it? SYN cookies are less like DTLS cookies, and I don't think we really need to list every cookie exchange protoocl

**Comment by hannestschofenig** [comment]
I actually think that we don't even list Photuris and IKE anymore when we talk about cookies. I was probably useful in the first version of DTLS when the concept was new and what the context of Photuris and IKE was helpful. Today, nobody knows anymore what Photuris and maybe even IKE is. It probably it confuses the reader more than it helps

**Comment by ekr** [comment]
I think this is fine as-is
