### ISSUE TITLE
Amplification factor

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls13-spec#78]
The cookie exchange is optional-ish.  If a server chooses not to try it, then should we recommend against sending lots and lots of data in response to a small ClientHello?  or use MUST in some way?  QUIC does, but ties itself into knots in the process.

**Comment by hannestschofenig** [comment]
The style of cookie exchange has not changed since earlier versions of DTLS. I am not aware of any problems with the DTLS cookie mechanism and hence I am wondering why we should change the text.

**Comment by ekr** [comment]
Given the stage we are at, I think we can leave DTLS where it is.

As Hannes says, DTLS 1.3 is the same as DTLS 1.2 in this respect, so it doesn't make matters worse and you can always retrofit a QUIC-style mechanism to DTLS if we want.
