### ISSUE TITLE
Determining the header format

### ISSUE THREAD

**Issue by fpalombini** [tlswg/dtls13-spec#81]
Section 4.1 states:

> 
>    Implementations can distinguish the two header formats by examining
>    the first byte:
> 
>    -  If the first byte is alert(21), handshake(22), or ack(proposed,
>       25), the record MUST be interpreted as a DTLSPlaintext record.

But 21, 22 and 25 are legitimate values for the first byte of the DTLSCiphertext. For example: 
* no CID
* 8-bit sequence number
* no length
* EE = 01
 
Gives 21. Same with 22 and 25. How to properly determine the header format in this case?
Am I missing something?

**Comment by ekr** [comment]
All DTLSCipherText values art of the form 001xxxxx and therefore are >= 32.

**Comment by fpalombini** [comment]
Sorry, my mistake came from interpreting "if the first byte is alert(21)" as 21 being an hex value.
