### ISSUE TITLE
Security guarantees are not equivalent to TLS 1.3

### ISSUE THREAD

**Issue by emanjon** [tlswg/dtls13-spec#82]
The Abstract states that: "The DTLS 1.3 protocol is intentionally based on the Transport Layer Security (TLS) 1.3 protocol and provides equivalent security guarantees."

This is not true when it comes to Order protection/non-replayability which is states as a guarantee in Appendix E.2 of RFC 8446. DTLS does not provide order protection and may not provide replay protection. I suggested this statement "equivalent security guarantees" is deleted (or rewritten) in the abstract and that some short text describing this is added to the Security Considerations.

**Comment by ekr** [comment]
Fixed.
