### ISSUE TITLE
CID needs path validation

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls13-spec#90]
(From https://github.com/tlswg/dtls-conn-id/issues/64)

If CID is successfully negotiated, an active man-in-the-middle can freely modify the source address of the UDP datagram — which is not integrity protected —  thus potentially causing amplified backscatter to be inadvertently generated by the receiver towards the spoofed address.  

(This does not work without CID because the spoofed packet would not reach the other end in the first place.)

To avoid this situation to arise, DTLS should provide a peer address validation sub-protocol — e.g., [QUIC’s path validation](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.8.2) — to be triggered when the receiver notices a change in the peer source address.

**Comment by hannestschofenig** [comment]
This issue will be addressed in a separate document. I did, however, add text similar to the one added to the DTLS 1.2 CID draft into the security consideration section. 

PR is here: 
https://github.com/tlswg/dtls13-spec/pull/96

**Comment by ekr** [comment]
Merged.
